FROM golang:1.23-alpine AS builder
WORKDIR /app
COPY go.mod go.sum ./
RUN go mod download
COPY . .
RUN go build -o /worker ./cmd/worker

FROM alpine:3.20
WORKDIR /app
COPY --from=builder /worker .
CMD ["./worker"]
